2024-10-06 10:19:29,867 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-06 10:19:39,481 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/import-export/mysite/shopapp/admin.py changed, reloading.
2024-10-06 10:19:40,577 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-06 10:21:59,825 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-06 10:23:03,566 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/import-export/mysite/shopapp/common.py changed, reloading.
2024-10-06 10:23:04,232 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-06 10:24:36,786 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/import-export/mysite/shopapp/common.py changed, reloading.
2024-10-06 10:24:37,610 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-06 10:30:43,160 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-06 10:31:00,227 [ERROR] django.request: Internal Server Error: /ru/admin/shopapp/order/import-orders-json/
Traceback (most recent call last):
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/import-export/mysite/shopapp/admin.py", line 139, in import_json
    save_json_orders(
  File "/home/sevacezar/PycharmProjects/Django/python_django/import-export/mysite/shopapp/common.py", line 33, in save_json_orders
    order_obj = Order.objects.create(
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 677, in create
    obj = self.model(**kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/fields/related_descriptors.py", line 284, in __set__
    raise ValueError(
ValueError: Cannot assign "<QuerySet [<User: admin>]>": "Order.user" must be a "User" instance.
2024-10-06 10:33:16,010 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/import-export/mysite/shopapp/common.py changed, reloading.
2024-10-06 10:33:17,441 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-06 10:33:27,000 [ERROR] django.request: Internal Server Error: /ru/admin/shopapp/order/import-orders-json/
Traceback (most recent call last):
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/import-export/mysite/shopapp/admin.py", line 139, in import_json
    save_json_orders(
  File "/home/sevacezar/PycharmProjects/Django/python_django/import-export/mysite/shopapp/common.py", line 38, in save_json_orders
    order_obj.products = products
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/fields/related_descriptors.py", line 659, in __set__
    raise TypeError(
TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use products.set() instead.
2024-10-06 10:34:13,230 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/import-export/mysite/shopapp/common.py changed, reloading.
2024-10-06 10:34:14,685 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-06 10:34:20,269 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/import-export/mysite/shopapp/common.py changed, reloading.
2024-10-06 10:34:21,798 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-06 10:36:31,273 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/import-export/mysite/shopapp/common.py changed, reloading.
2024-10-06 10:36:32,187 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-06 10:36:43,710 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/import-export/mysite/shopapp/common.py changed, reloading.
2024-10-06 10:36:44,258 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-06 10:36:49,988 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/import-export/mysite/shopapp/common.py changed, reloading.
2024-10-06 10:36:50,819 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-06 10:36:55,250 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/import-export/mysite/shopapp/common.py changed, reloading.
2024-10-06 10:36:56,254 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-06 10:37:05,452 [ERROR] django.request: Internal Server Error: /ru/admin/shopapp/order/import-orders-json/
Traceback (most recent call last):
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2117, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'QuerySet'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/import-export/mysite/shopapp/admin.py", line 139, in import_json
    save_json_orders(
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/sevacezar/PycharmProjects/Django/python_django/import-export/mysite/shopapp/common.py", line 40, in save_json_orders
    order_obj.products.add(products)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/fields/related_descriptors.py", line 1201, in add
    self._add_items(
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/fields/related_descriptors.py", line 1461, in _add_items
    target_ids = self._get_target_ids(target_field_name, objs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/fields/related_descriptors.py", line 1395, in _get_target_ids
    target_ids.add(target_field.get_prep_value(obj))
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/fields/related.py", line 1155, in get_prep_value
    return self.target_field.get_prep_value(value)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2119, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <QuerySet [<Product: Product(pk=3, name='AirPods')>, <Product: Product(pk=1, name='Iphone')>]>.
2024-10-06 10:37:37,006 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/import-export/mysite/shopapp/common.py changed, reloading.
2024-10-06 10:37:38,814 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-06 10:37:42,201 [ERROR] django.request: Internal Server Error: /ru/admin/shopapp/order/import-orders-json/
Traceback (most recent call last):
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2117, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'QuerySet'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/import-export/mysite/shopapp/admin.py", line 139, in import_json
    save_json_orders(
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/sevacezar/PycharmProjects/Django/python_django/import-export/mysite/shopapp/common.py", line 40, in save_json_orders
    order_obj.products.add(products)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/fields/related_descriptors.py", line 1201, in add
    self._add_items(
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/fields/related_descriptors.py", line 1461, in _add_items
    target_ids = self._get_target_ids(target_field_name, objs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/fields/related_descriptors.py", line 1395, in _get_target_ids
    target_ids.add(target_field.get_prep_value(obj))
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/fields/related.py", line 1155, in get_prep_value
    return self.target_field.get_prep_value(value)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2119, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <QuerySet [<Product: Product(pk=3, name='AirPods')>, <Product: Product(pk=1, name='Iphone')>]>.
2024-10-06 10:37:58,310 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/import-export/mysite/shopapp/common.py changed, reloading.
2024-10-06 10:38:00,053 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 07:23:51,784 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 07:23:59,868 [DEBUG] shopapp.views: Refs for shop index: [{'name': 'products/', 'description': 'List of products'}, {'name': 'orders/', 'description': 'List of orders'}]
2024-10-08 07:23:59,869 [INFO] shopapp.views: Rendering shop index
2024-10-08 07:27:22,256 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/mysite/settings.py changed, reloading.
2024-10-08 07:27:22,975 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 07:27:24,535 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/mysite/settings.py changed, reloading.
2024-10-08 07:29:29,251 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 07:30:26,382 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/myauth/views.py changed, reloading.
2024-10-08 07:30:26,871 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 07:30:44,720 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/myauth/views.py changed, reloading.
2024-10-08 07:30:45,401 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 07:30:51,882 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/myauth/views.py changed, reloading.
2024-10-08 07:30:52,545 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 07:31:01,110 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/myauth/views.py changed, reloading.
2024-10-08 07:31:01,683 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 07:31:05,013 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/myauth/views.py changed, reloading.
2024-10-08 07:31:05,887 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 07:31:09,706 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/myauth/views.py changed, reloading.
2024-10-08 07:31:10,289 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 07:33:22,842 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/urls.py changed, reloading.
2024-10-08 07:33:23,518 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 07:33:26,940 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/urls.py changed, reloading.
2024-10-08 07:33:27,401 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 07:35:20,900 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/urls.py changed, reloading.
2024-10-08 07:35:21,399 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 07:35:24,768 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/urls.py changed, reloading.
2024-10-08 07:35:25,256 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 07:35:27,783 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/urls.py changed, reloading.
2024-10-08 07:35:28,389 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 07:35:32,956 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/urls.py changed, reloading.
2024-10-08 07:35:33,581 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 07:35:56,426 [DEBUG] shopapp.views: Refs for shop index: [{'name': 'products/', 'description': 'List of products'}, {'name': 'orders/', 'description': 'List of orders'}]
2024-10-08 07:35:56,427 [INFO] shopapp.views: Rendering shop index
2024-10-08 07:40:29,737 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 07:40:30,483 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 07:44:46,211 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 07:45:35,269 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 07:45:35,728 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 07:47:57,754 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 07:48:06,807 [DEBUG] shopapp.views: Refs for shop index: [{'name': 'products/', 'description': 'List of products'}, {'name': 'orders/', 'description': 'List of orders'}]
2024-10-08 07:48:06,808 [INFO] shopapp.views: Rendering shop index
2024-10-08 07:48:17,105 [DEBUG] shopapp.views: Refs for shop index: [{'name': 'products/', 'description': 'List of products'}, {'name': 'orders/', 'description': 'List of orders'}]
2024-10-08 07:48:17,106 [INFO] shopapp.views: Rendering shop index
2024-10-08 07:48:28,425 [DEBUG] shopapp.views: Refs for shop index: [{'name': 'products/', 'description': 'List of products'}, {'name': 'orders/', 'description': 'List of orders'}]
2024-10-08 07:48:28,427 [INFO] shopapp.views: Rendering shop index
2024-10-08 07:50:05,320 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 07:50:06,082 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 08:18:44,358 [DEBUG] shopapp.views: Refs for shop index: [{'name': 'products/', 'description': 'List of products'}, {'name': 'orders/', 'description': 'List of orders'}]
2024-10-08 08:18:44,359 [INFO] shopapp.views: Rendering shop index
2024-10-08 08:18:45,494 [DEBUG] shopapp.views: Refs for shop index: [{'name': 'products/', 'description': 'List of products'}, {'name': 'orders/', 'description': 'List of orders'}]
2024-10-08 08:18:45,494 [INFO] shopapp.views: Rendering shop index
2024-10-08 08:18:46,189 [DEBUG] shopapp.views: Refs for shop index: [{'name': 'products/', 'description': 'List of products'}, {'name': 'orders/', 'description': 'List of orders'}]
2024-10-08 08:18:46,189 [INFO] shopapp.views: Rendering shop index
2024-10-08 08:18:47,073 [DEBUG] shopapp.views: Refs for shop index: [{'name': 'products/', 'description': 'List of products'}, {'name': 'orders/', 'description': 'List of orders'}]
2024-10-08 08:18:47,073 [INFO] shopapp.views: Rendering shop index
2024-10-08 08:19:08,777 [DEBUG] shopapp.views: Refs for shop index: [{'name': 'products/', 'description': 'List of products'}, {'name': 'orders/', 'description': 'List of orders'}]
2024-10-08 08:19:08,778 [INFO] shopapp.views: Rendering shop index
2024-10-08 08:19:10,028 [DEBUG] shopapp.views: Refs for shop index: [{'name': 'products/', 'description': 'List of products'}, {'name': 'orders/', 'description': 'List of orders'}]
2024-10-08 08:19:10,028 [INFO] shopapp.views: Rendering shop index
2024-10-08 08:21:14,355 [DEBUG] shopapp.views: Refs for shop index: [{'name': 'products/', 'description': 'List of products'}, {'name': 'orders/', 'description': 'List of orders'}]
2024-10-08 08:21:14,355 [INFO] shopapp.views: Rendering shop index
2024-10-08 08:22:22,464 [DEBUG] shopapp.views: Refs for shop index: [{'name': 'products/', 'description': 'List of products'}, {'name': 'orders/', 'description': 'List of orders'}]
2024-10-08 08:22:22,465 [INFO] shopapp.views: Rendering shop index
2024-10-08 08:22:25,559 [DEBUG] shopapp.views: Refs for shop index: [{'name': 'products/', 'description': 'List of products'}, {'name': 'orders/', 'description': 'List of orders'}]
2024-10-08 08:22:25,559 [INFO] shopapp.views: Rendering shop index
2024-10-08 08:28:47,355 [ERROR] django.request: Internal Server Error: /ru/accounts/about-me/
Traceback (most recent call last):
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 502, in parse
    compile_func = self.tags[command]
KeyError: 'else'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/templatetags/cache.py", line 84, in do_cache
    nodelist = parser.parse(("endcache",))
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 35: 'else', expected 'endcache'. Did you forget to register or load this tag?
2024-10-08 08:38:46,471 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 08:38:47,603 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 08:38:49,362 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 08:38:49,783 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 08:45:08,241 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 08:51:32,441 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/mysite/settings.py changed, reloading.
2024-10-08 08:51:32,950 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 08:51:47,557 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/mysite/settings.py changed, reloading.
2024-10-08 08:51:47,986 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 08:52:01,482 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/mysite/settings.py changed, reloading.
2024-10-08 08:52:01,896 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 08:52:04,153 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/mysite/settings.py changed, reloading.
2024-10-08 08:52:04,582 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 08:55:55,646 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:23:06,240 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:24:12,943 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/mysite/settings.py changed, reloading.
2024-10-08 09:24:13,387 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:24:14,659 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/mysite/settings.py changed, reloading.
2024-10-08 09:24:15,307 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:24:17,610 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/mysite/settings.py changed, reloading.
2024-10-08 09:24:18,082 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:24:36,213 [DEBUG] shopapp.views: Refs for shop index: [{'name': 'products/', 'description': 'List of products'}, {'name': 'orders/', 'description': 'List of orders'}]
2024-10-08 09:24:36,217 [INFO] shopapp.views: Rendering shop index
2024-10-08 09:24:43,655 [WARNING] django.request: Not Found: /ru/shop/users/
2024-10-08 09:24:58,124 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "/home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py", line 247, in get_queryset
    orders = Order.objects.filter(user=user).prefetch_related('products')
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/fields/related_lookups.py", line 158, in get_prep_lookup
    return super().get_prep_lookup()
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/db/models/lookups.py", line 360, in get_prep_lookup
    raise ValueError(
ValueError: The QuerySet value for an exact lookup must be limited to one result using slicing.
2024-10-08 09:25:39,763 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:25:40,405 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:25:44,988 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:25:45,710 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:30:55,388 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:30:55,858 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:32:05,609 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 502, in parse
    compile_func = self.tags[command]
KeyError: 'cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/template/base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 9: 'cache', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
2024-10-08 09:33:31,484 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:33:31,998 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:33:46,544 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:33:47,020 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:33:49,745 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:33:50,412 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:33:53,016 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:33:53,438 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:34:54,449 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:34:55,122 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:34:57,909 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:34:58,906 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:35:02,610 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:35:03,099 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:36:41,998 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:36:42,431 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:36:52,065 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:36:52,672 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:36:58,356 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:36:58,801 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:37:01,290 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:37:01,724 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:37:03,240 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:37:03,776 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:37:11,376 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:37:11,855 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:37:17,368 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:37:17,891 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:37:25,629 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:37:26,102 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:37:33,137 [ERROR] django.request: Internal Server Error: /ru/shop/users/100/orders/
Traceback (most recent call last):
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
  File "/home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py", line 255, in get_context_data
    context['owner'] = self.owner
AttributeError: 'UserOrdersListView' object has no attribute 'owner'
2024-10-08 09:39:05,991 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:39:06,570 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:39:10,030 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:39:11,040 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:39:25,659 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:39:26,134 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:39:28,111 [ERROR] django.request: Internal Server Error: /ru/shop/users/100/orders/
Traceback (most recent call last):
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
  File "/home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py", line 256, in get_context_data
    context['owner'] = self.owner
AttributeError: 'UserOrdersListView' object has no attribute 'owner'
2024-10-08 09:39:42,412 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:39:43,197 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:39:49,401 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:39:49,976 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:39:53,612 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:39:54,794 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:39:55,932 [ERROR] django.request: Internal Server Error: /ru/shop/users/100/orders/
Traceback (most recent call last):
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
  File "/home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py", line 256, in get_context_data
    context['owner'] = self.owner
AttributeError: 'UserOrdersListView' object has no attribute 'owner'
2024-10-08 09:44:19,987 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:44:20,601 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:44:34,539 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:44:35,034 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:44:44,650 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:44:45,276 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:44:48,836 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:44:49,328 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:44:59,976 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:45:00,513 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:45:03,505 [WARNING] django.request: Not Found: /ru/shop/users/100/orders/
2024-10-08 09:45:09,472 [WARNING] django.request: Not Found: /ru/shop/users/100/orders/
2024-10-08 09:45:10,411 [WARNING] django.request: Not Found: /ru/shop/users/100/orders/
2024-10-08 09:47:30,337 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:47:30,848 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:47:35,299 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:57:15,828 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:57:26,870 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
TypeError: UserOrdersExportView.get() got an unexpected keyword argument 'user_id'
2024-10-08 09:58:13,806 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:58:14,756 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 09:58:18,909 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 09:58:19,529 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 10:01:19,359 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 10:01:19,997 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 10:01:23,579 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 10:01:25,511 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 10:01:27,143 [WARNING] django.request: Bad Request: /ru/shop/users/100/orders/export/
2024-10-08 10:01:41,093 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 10:01:42,337 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 10:03:26,724 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 10:03:27,190 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 10:03:29,776 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 10:03:31,007 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 10:10:00,594 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 10:10:39,345 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 10:10:40,357 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 10:15:30,805 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 10:16:18,006 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 10:16:18,527 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 10:16:27,107 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 10:16:27,886 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 10:16:47,610 [ERROR] django.request: Internal Server Error: /ru/shop/users/2/orders/export/
Traceback (most recent call last):
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py", line 349, in get
    time.sleep(10)
AttributeError: type object 'datetime.time' has no attribute 'sleep'
2024-10-08 10:17:06,686 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 10:17:07,192 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 10:17:10,426 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 10:17:11,101 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 10:17:13,869 [ERROR] django.request: Internal Server Error: /ru/shop/users/2/orders/export/
Traceback (most recent call last):
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py", line 349, in get
    time.sleep(10)
AttributeError: 'builtin_function_or_method' object has no attribute 'sleep'
2024-10-08 10:17:27,069 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 10:17:27,695 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 10:18:22,813 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/mysite/settings.py changed, reloading.
2024-10-08 10:18:23,270 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 10:18:25,611 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/mysite/settings.py changed, reloading.
2024-10-08 10:18:26,067 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-08 10:18:56,269 [INFO] django.utils.autoreload: /home/sevacezar/PycharmProjects/Django/python_django/Django_Cache/mysite/shopapp/views.py changed, reloading.
2024-10-08 10:18:56,838 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-10-09 15:12:49,300 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
